name: 'Run Cypress tests on Currents dev'
description: 'Runs Cypress end-to-end test on Currents dev platform'
inputs:
  github_token:
    description: 'Github token'
    required: false
  username:
    description: "Username for test run"
    required: true
  password: 
    description: "Password for Username"
    required: true
  env:
    description: "Name of the env"
    required: true
    default: staging
  customEnv:
    description: "Url of custom env (PR deploy, dev/prod env)"
    required: false
  url:
    description: "One of the env urls we usually use for tests: dev, stage, prod"
    required: true
    default: 'https://bowery-staging.herokuapp.com'
  spec_file:
    description: "--spec flag arg in cypress cli"
    required: true
    default: "cypress/integration/**/*.spec.ts"
  tags:
    description: "Tags for cypress-grep"
    required: true
    default: grep=,grepTags=@smoke,burn=
  record_key:
    description: "record key used to activate test results recording on Dashboard"
    required: true
  role_to_assume:
    description: "role which used to connect to AWS"
    required: true

runs:
  using: "composite"
  steps:

    - name: Show action's inputs
      shell: bash
      run: |
          echo "github_token=${{ inputs.github_token }}"
          echo "username=${{ inputs.USERNAME }}"
          echo "env=${{ inputs.env }}"
          echo "customEnv=${{ inputs.customEnv }}"
          echo "spec_file=${{ inputs.spec_file }}"
          echo "tags=${{ inputs.tags }}"
          echo "record_key=${{ inputs.record_key }}"

    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: 'Bowery-RES/webapp-ui-automation'
        token: ${{ inputs.github_token }}

    - name: Cache node modules
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Cache node modules
      run: npm i cypress@9.6.0 -g
      shell: bash
    
    - name: Install Currents globally
      run: npm i @currents/cli -g
      shell: bash

    - name: Install Dependencies
      run: npm install
      shell: bash

    - name: Configure secrets
      uses: aws-actions/configure-aws-credentials@v1
      with:
          role-to-assume: arn:aws:iam::814827541967:role/GithubOIDC-Role-QMKR3DR5WV3B
          aws-region: 'us-east-1'

    - name: Set secrets to GH environment
      uses: Bowery-RES/action-aws-secrets@v1.1
      with:
          secrets: |
            Github/Cypress/User_Roles
          namespace: false

    - name: Run Cypress not snapshot tests on Currents.dev
      run: currents run --config baseUrl=${{ inputs.customEnv == '' && inputs.url ||  inputs.customEnv }} --tag ${{ inputs.env }} --spec ${{ inputs.spec_file }} --env ${{ inputs.tags }} --browser chrome --record --parallel --key ${{ inputs.record_key }} --ci-build-id "${{ github.repository }}-${{ github.run_id }}-${{ github.run_attempt}}"
      shell: bash  
      env:
        CYPRESS_USERNAME: ${{ inputs.USERNAME }}
        CYPRESS_PASSWORD: ${{ inputs.PASSWORD }}
        CYPRESS_url: ${{ inputs.env }}
        CYPRESS_customEnv: ${{inputs.customEnv }}
        CYPRESS_grepFilterSpecs: "true"
